name: Hugo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true  # <-- this is needed to checkout theme which normally come from separate git repository

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: 0.87.0
        image: ext-asciidoctor